spring.application.name=food-delivery-api

spring.datasource.url=jdbc:h2:file:./data/fooddelivery
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:9mK7xP2qL8vN4rT6yW1zA5cF8hJ3uB7eQ2nX9sD4gR6p}
jwt.expiration-seconds=3600

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false